### ISSUE TITLE
Problem wrapping .erb views

### ISSUE THREAD

**Issue by dunphyben** [dcdeiv/simple-sidebar#13]
I am using the [HTML5 Boilerplate](https://github.com/h5bp/html5-boilerplate), which utilizes `.html.erb` views (i.e. `<%= yield %>` ). I can get the sidebar functioning just fine, except that it does not include the partials.

The structure of the pages are Layout + Page  
The __layout.erb__ includes:  
```
<head></head>
<body>
  <%= yield %>
</body>
<footer></footer>
```
Each page simply includes:  
```
<title></title>
<content></content>
```

I have tried placing the `<div id="wrapper"></div>` around various locations: just the `<%= yield %>` on the `layout.html.erb`, just on the individual page itself, or in both locations. This has been to no avail: I cannot get the content of the partials to move with the navbar. What's worse, is that even if I type content on the `layout.html.erb` directly between the wrapper, it still does not move with the navbar. This leads me to believe that it may not necessarily be an issue directly with the partials layout.  
Am I missing something? 

See the js bin here https://jsbin.com/zepisen/edit?html,css,output

**Comment by dcdeiv** [comment]
The problem is that you gave an ID `<div id="wrapper">` to the wrapper div and then called it with a class `.wrapper {}`.

The solution is pretty simple:

```html
<div id="wrapper">
  <%= yield %>

  <div class="examplebody">
    <p>Example Body Content within the wrapper not responding to the menu </p>  
  </div>
</div>
```

```css
#wrapper {
    position: relative;
}
```
