### ISSUE TITLE
overflow after close

### ISSUE THREAD

**Issue by fredroo** [dcdeiv/simple-sidebar#15]
After close

show this error

![error](https://cloud.githubusercontent.com/assets/6863089/9642910/37fb3060-5195-11e5-931f-3dc4ff1e5677.png)
`<body style="overflow: auto;">`

**Comment by dcdeiv** [comment]
There's probably an error in your CSS. Can you please test this page? http://dcdeiv.github.io/simple-sidebar/

**Comment by fredroo** [comment]
works fine

my code:
`$(document).ready(function() {
    $('#sidebar').simpleSidebar({
        opener: '#toggle-sidebar',
        top: 145,
      animation: {
          easing: 'easeOutQuint'
      },
        sidebar: {
            align: 'left',
            width: 300,
            closingLinks: '.close-sidebar',
            css: {
                    top: 145
                }
        }
    });
});`

**Comment by dcdeiv** [comment]
I think that there's a problem with the wrapper. You should use margin-top instead of top (which causes this problem).
Can you please check your stylesheet?

```CSS
.main-content {
    position: relative;
    margin-top: 42px; //the height of the top navbar
    padding: 1em;
}
```

Plus what do you want to get with `css: { top: 145 }` ?
Something like this? http://dcdeiv.github.io/simpler-sidebar/right-top/
This option is not yet available nor is tested but if you think it works in this way I will test it as soon as I can!

**Comment by dcdeiv** [comment]
If you can't get rid of that issue, please use one of these [examples](https://github.com/dcdeiv/simple-sidebar/tree/master/tests) you can find in the package! But if you test them on Chrome you will get some errors, especially if you test dynamic pages offline. Try use Firefox for dynamic pages while testing offline!

**Comment by fredroo** [comment]
in codepen.io no problem with same code

probably conflict with other jquery

thanks

**Comment by fredroo** [comment]
@dcdeiv 

problem with my custom css (solved)

thanks again

**Comment by dcdeiv** [comment]
you're welcome!
