### ISSUE TITLE
questions about simple-sidebar (right side)

### ISSUE THREAD

**Issue by jldouglas58** [dcdeiv/simple-sidebar#5]
I am new to this site and terms githug, json, bower.  I downloaded the zip file for this sidebar, but I am lost as to how to install it.  please help

**Comment by dcdeiv** [comment]
I'll write a simpler guide as soos as I can!
Dont' worry. The Simple-Sidebar does all the dirty work for you. You won't need a CSS to move anything. You will need a CSS just to make the sidebar look more fancy in the way you like.

**Comment by jldouglas58** [comment]
I added a container within the wrapper with a height of 2500px.  I am basically trying to merge code with you the sidebar code.  first step was to add the container.  I can see the scroll on the right side of the screen but as soon as I click the button to open the menu, my scroll is gone.  I will have to refresh to get it back.  I uploaded the code to http://jandswebsitedesigns.com/simple/

**Comment by dcdeiv** [comment]
It is meant to be like this. In every web-app when you open the sidebar you won't be able to scroll the content of the page. It would be silly to allow content to be on top when the sidebar is meant to be on top. This is not an issue/bug.

**Comment by jldouglas58** [comment]
okay this is what I meant.  I open up the page, I click open the menu, then
decide to close the menu.  I can't scroll down after that because scrolling
has been disable,  even though I set up a container with enough height to
test it.

On Sat, Mar 21, 2015 at 1:53 PM, Davide DC <notifications@github.com> wrote:

> It is meant to be like this. In every web-app when you open the sidebar
> you won't be able to scroll the content of the page. It would be silly to
> allow content to be on top when the sidebar is meant to be on top. This is
> not an issue/bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcdeiv/simple-sidebar/issues/5#issuecomment-84421595>.
>



-- 
"The Lord is my light and my salvation—whom shall I fear?  The Lord is the
stronghold of my life—of whom shall I be afraid?"
Psalm 27:1

**Comment by dcdeiv** [comment]
Can you please try with this version? https://github.com/dcdeiv/simple-sidebar/releases/tag/v1.1.0

**Comment by jldouglas58** [comment]
I sure will.  Am I to conclude that the only thing that changes in the code you helped me with is the two javascript files?

**Comment by jldouglas58** [comment]
the only thing that changes is the two script files correct?


On Sat, Mar 21, 2015 at 2:06 PM, Davide DC <notifications@github.com> wrote:

> Can you please try with this version?
> https://github.com/dcdeiv/simple-sidebar/releases/tag/v1.1.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcdeiv/simple-sidebar/issues/5#issuecomment-84423742>.
>



-- 
"The Lord is my light and my salvation—whom shall I fear?  The Lord is the
stronghold of my life—of whom shall I be afraid?"
Psalm 27:1

**Comment by dcdeiv** [comment]
yes. Just replace the file with this one from v1.1.0 and you won't need to change any html line.
But please. Add some more text and content in the page first.

**Comment by jldouglas58** [comment]
yes sir.  :-)

**Comment by dcdeiv** [comment]
So I updated everything and bring back to v1.1.0 now called v1.1.2.

**Comment by jldouglas58** [comment]
Can you please tell me where I can post code along with a question?



On Sat, Mar 21, 2015 at 3:46 PM, Davide DC <notifications@github.com> wrote:

> So I updated everything and bring back to v1.1.0 now called v1.1.2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcdeiv/simple-sidebar/issues/5#issuecomment-84452364>.
>



-- 
"The Lord is my light and my salvation—whom shall I fear?  The Lord is the
stronghold of my life—of whom shall I be afraid?"
Psalm 27:1

**Comment by dcdeiv** [comment]
Please, refer to this guide. https://guides.github.com/features/mastering-markdown/

I just released a new package of Simple-Sidebar which is the (v1.1.2)[https://github.com/dcdeiv/simple-sidebar/releases/tag/v1.1.2] please, be sure you use this version first. In the end, I cannot help you here with your website! This form should be used for issues and to track bugs!
